<?php

namespace Tests\Browser;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class CreateLeadTest extends DuskTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        BrowserShared::setupInstallation();
        $this->user = BrowserShared::$user;

    }

    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testNavigateLeads()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs($this->user)
                ->maximize()
                ->visit('/admin/leads')
                ->assertSee('Active Leads');
        });
    }

    public function testCreateLead()
    {
        $this->browse(function (Browser $browser) {
            $browser->click('.btn-outline-info')
                ->waitForText("New Lead")
                ->type('company', "New Company")
                ->type('contact', "John Smith")
                ->type('email', "test@newlead.com")
                ->click(".btn-primary")
                ->waitForText("Manage the lead")
                ->assertSee("Manage the lead profile");
        });
    }



    public function testUpdatesDetails()
    {
        $this->browse(function (Browser $browser) {
            $browser->waitForText("Contact Information")
                ->type('address', "123 Test Lead")
                ->type('city', "Testville")
                ->type('state', "GA")
                ->type('zip', '30123')
                ->click('.updateDetails')
                ->assertSee("Manage the lead profile");
                });
    }

}
