<?php

namespace Tests\Browser;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class DiscoveryTest extends DuskTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        BrowserShared::setupInstallation();
        $this->user = BrowserShared::$user;

    }

    /**
     * A Dusk test example.
     *
     * @return void
     */
    public function testNavigateDiscovery()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs($this->user)
                ->maximize()
                ->visit('/admin/discovery')
                ->assertSee('Discovery Builder');
        });
    }

    public function testCreateFirst()
    {
        $this->browse(function (Browser $browser) {
            $browser->type('question', "How many things are you looking to buy?")
                ->click(".btn-primary")
                ->assertSee('How many');
        });
    }


    public function testCreateSecond()
    {
        $this->browse(function (Browser $browser) {
            $browser->type('question', "Do you want better service?")
                ->select('type', 'Dropdown')
                ->click(".btn-primary")
                ->assertSee('Do you want')
                ->clickLink("Click to Edit")
                ->type('.form-control-sm', "Yes,No\n")
                ->waitForText("Yes,No")
                ->assertSee("Yes,No");
        });
    }


}

