<?php

namespace Tests\Browser;

use Illuminate\Foundation\Testing\DatabaseMigrations;
use Laravel\Dusk\Browser;
use Tests\DuskTestCase;

class SettingsTest extends DuskTestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        BrowserShared::setupInstallation();
        $this->user = BrowserShared::$user;

    }

    /**
     * A Dusk test example.
     *
     * @return void
     * @throws \Throwable
     */
    public function test_can_see_settings()
    {
        $this->browse(function (Browser $browser) {
            $browser->loginAs($this->user)
                ->maximize()
                ->visit('/admin/settings')
                ->assertSee('Logic Settings');
        });
    }

    public function test_can_update_address_license()
    {
        $this->browse(function (Browser $browser) {
            $browser->type('s_4', "123 Test Way")
                ->type('s_6', 'Atlanta, GA 30123')
                ->waitFor('.wait')
                ->click('.wait')
                ->assertSee('BRAND SETTINGS');
        });
    }



}
